version: '3'
services:
  mountebank:
    image: jibsoft/mountebank
    ports:
      - "2525:2525"
      - "4545:4545"
    volumes:
      - ./imposters:/imposters
    command: --configfile /imposters/imposters.ejs --allowInjection
